CatalysmsServerManager/7-days-to-die-server-manager

- api/controllers/SdtdServer/server-tile.js
- api/models/SdtdServer.js
- assets/js/sdtdServer/map.js
- config/routes.js
- package-lock.json
- package.json
- views/sdtdServer/partials/map.ejs
* Add new helper function to build the hash that 7daystodie-api-wrapper needs for config
* Add new proxy route for proxying tiles
* Update leaflet to use new proxy route (Also means auth no longer needs to be exposed to front end)
Unrelated:
* Add nodemon as dev deps so it works on systems without it globally installed
> Proxy Web Tiles

- .gitignore
- .travis.yml
- api/controllers/CustomCommand/create-command.js
- api/helpers/meta/check-donator-status.js
- api/hooks/sdtdLogs/logProcessor.js
- config/bootstrap.js
- config/datastores.js
- config/http.js
- package-lock.json
- package.json
- test/integration/customCommand/createCustomCommand.test.js
- test/lifecycle.test.js
- test/mocha.opts
A bunch of tiny updates
* Update mocha, so configs are all in package.json todo with nyc
* updated configs to pre-load lifecycle file
* you can now just run `mocha` or `mocha --watch`
* Moved mochawesome from test dir that was messing up recusrive watching
* A bunch of minor updates to support redis/mysql not being run while testing (I have them in docker-compose, but not on the host itself)
> Upgrade mocha and tests

- .dockerignore
- Dockerfile
- scripts/itemIconsUpdate.sh
I found docker-compose super slow to build the image.
* Ignore db-data and cache-data so it doesn't need to copy it into the image
* Copy with chown so you don't need to do the expensive chown after npm install
* Reduce the complexity of itemIconsUpdate (add -e to bail on error and -x to debug whats going on)
> Reduce the amount of effort needed to create docker image

- api/hooks/sdtdLogs/logProcessor.js
- config/bootstrap.js
- package-lock.json
- package.json
- test/integration/hooks/sdtdLogs/logProcessor.test.js
- test/lifecycle.test.js
Switch to using sinon and stubbing out function. 
* Has ability to restore after tests (in theory no test can break another test)
* Will yell if your stubbing something that doesn't exist (can detect renamed functions, but not change in prototype)
* Make a fake sails helper for 7daystodie-api-wrapper calls, so they can be stubbed out in tests
See sinon happy complain if we are stubbing the wrong thing (First was sails.helpers.sdtdapi not sails.helpers.sdtdApi, second was wrong function name)
I so want to replace any direct calls to 7daystodie-api-wrapper but will do so when more tests are in place.
> Refactor so calls to 7daystodie-api-wrapper can be tested

- Dockerfile
- docker-compose.yml
- scripts/healthcheck.js
> Docker build needs a proper healthcheck

- Dockerfile
- api/controllers/AdminController.js
- api/controllers/CommandReply/add-reply.js
- api/controllers/CommandReply/get-reply.js
- api/controllers/SdtdServer/update-connection-info.js
- api/helpers/get-queue-object.js
- api/helpers/redis/del.js
- api/helpers/redis/get.js
- api/helpers/redis/incr.js
- api/helpers/redis/lrange.js
- api/helpers/redis/rpush.js
- api/helpers/redis/set.js
- api/helpers/roles/check-permission.js
- api/hooks/bullboard.js
- api/hooks/discordChatBridge/chatBridgeChannel.js
- api/hooks/sdtdLogs/LoggingObject.js
- api/hooks/sdtdLogs/index.js
- api/hooks/sdtdLogs/logProcessor.js
- api/policies/isCsmmAdmin.js
- api/policies/isLoggedIn.js
- api/policies/roles/hasAccess.js
- config/custom.js
- config/datastores.js
- package-lock.json
- package.json
- worker.js
As usual, I try to make each commit seperate so they can be cherry picked/reverted later
* make the default docker file run both worker and web app, not just webapp
* confirm session object exists and is loaded before trying to use it
* Report full errors instead of just message, so we can debug with stacktrace
* Meaty commit - Add bullboard for stats, seperate the log processing job queue into a seperate worker process
* Migrate CSMM_ADMINS all over the place, to sails.config.custom.adminSteamIds
* non production datastores can be mysql/redis if enabled
* Redis wrappers now properly handle redis not being enabled
* Switch reply types to direct require so they dont break if hooks are not loaded
> Seperate bull queue

- config/customLog.js
- config/log.js
- create_tables.js
Upgrade custom logger to allow silly
timeout for create table is now 60 seconds
> Upgrade custom logger to allow silly and extend create table timeout

- api/hooks/sdtdLogs/LoggingObject.js
Instead of adding jobs on an interval, only add new jobs after the previous one has completed (or failed)
> Refactor logic for adding queue jobs

- api/hooks/sdtdLogs/LoggingObject.js
- test/lifecycle.test.js
- test/unit/hooks/sdtdlogs/LoggingObject.test.js
Two major issues
1) When emptyResponses hit 5,it would reset to 0, but then get reset to the last log line # again
2) Now that there is so many ignored log lines, it returns [] more often, which isn't stalled, just no results. So i changed it to check the log line #, as long as thats not staying the same, its still working
> Fix ticket 30

- api/helpers/sdtd/validate-item-name.js
- test/unit/helpers/sdtd/validate-item-name.test.js
> Refactor validate item name helper + add tests

- api/controllers/Player/give-item.js
- api/helpers/sdtd/validate-item-name.js
since the keys between manager and api don't match up correctly
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/commit/ec4b5d5f49f2df13eb6a5ae9048b1d5957537b19
I'm honestly not sure what the best way to handle this is. Maybe mock out the fetchJson function instead, and ... nope, it takes in an object too. 
Maybe stub out fetch json, but get each function to checkServer(server) so it errors if undefined or something.
> Make sure we use SdtdServer.getAPIConfig when calling sdtdapi calls

- api/winston-loki-transport.js
- config/customLog.js
So 2 options:
1) setting `CSMM_LOG_JSON=true` will make winston output to console as json, that way promtail can be setup to process it as json and stuff
2) `LOKI_URL=http://127.0.0.1:3100/loki/api/v1/push` will upload every message directly to loki (see belong screenshot)
You can do both or neither, doesn't matter. Both should mean stacktraces are grouped together.
Things I've found about loki
labels are global, which is cool. `{app="csmm",level="error"}` works great. But any random per line info (eventually, like server id) is harder to support. 
Winston 3 makes it easy and straight forward to add meta data per message, but we can't make it work cleanly with sails. Essentially sails.logger.info("foo", "bar") is recorded as "foo bar" in winston 2. sails.logger.info("foo %s", "bar") is …
> Add support for loki logger

- api/hooks/discordBot/commands/sdtd/serverInfo.js
> Drop on death value is reported incorrectly for serverinfo command

- api/hooks/countryBan/index.js
- api/hooks/discordNotifications/notifications/countrybanKick.js
- test/lifecycle.test.js
- test/unit/hooks/countryBan/countryBan.test.js
> GBL Notification bug

- api/hooks/discordBot/commands/sdtd/lookup.js
- api/hooks/discordBot/commands/sdtd/player.js
The problem is that
https://7dtd.illy.bz/browser/binary-improvements/MapRendering/Web/API/GetPlayerList.cs#L28
returns 25 players by default. The code assumes the user will be in the
list of players. Sadly the machinepack library doesn't let you specify
more anyways. Plus I don't think it actually matters since its really
just grabbing a list of players, and it'll return the most recent 25
users.
So if someone is looking up an older user, we already know we have the
db version and its unlikely changed. So return the db version when it
cant find the return from the server.
> Fix #230 - lookup breaking

- create_tables.js
Some of the docs and scripts called create_tables.js directly, so
unti all the docs are fully upgraded, and all images are fully upgraded,
just call the npm script (which should have been the documented way
originally)
> Make create_tables.js an alias for db:migrate

- api/controllers/SdtdServer/add-server.js
I think this got lost somewhere during the scaling refactorings of the logging hook. No tests because not much time and this is a big blocker for new users.
> Fix logging hook not started after adding a server

- docker-compose.yml
Changes port 8000 to port 1337 to match with both the port csmm-web runs on, as well as the port in .env.example
> Change example docker-compose to match .env.example for port

- api/hooks/discordBot/commands/sdtd/top.js
Resolves #349.
Added top command validation for arguments.
Tell me if you want to bypass capitalization of argument value and to only block argument values that aren't inside **oneOf** array irrespective of their capitalization, it is just a matter of `.toLowerCase()`.
> Fix top Discord command validation of argument

- api/controllers/User/find-guilds-managed-by-user.js
Fix for issue #365 
Early return badRequest if the user is either undefined or null.
> Fix issue where null discord user throws TypeError

- README.md
Added new link for support which will point to the support page of CSM site and test_coverage is currently not available so removes it.
> Fix codecoverage badge in README

- .github/workflows/CI.yml
This step errors so often, making the check fail while the tests actually passed. I don't think it's super useful anyway.
> Remove upload test artifact from CI

- .env.example
- api/hooks/discordBot/index.js
This PR aims to fix #350 
* added invite key
* included `.env` entry
* linked accordingly
> Make discord bot errors link to dev discord instead of bot owners

- api/controllers/BannedItemList/set-banned-item-status.js
- api/controllers/SdtdServer/update-connection-info.js
- api/helpers/meta/set-server-active.js
- api/helpers/meta/set-server-inactive.js
- api/hooks/bannedItems/index.js
- api/hooks/countryBan/index.js
- api/hooks/customDiscordNotification/index.js
- api/hooks/customHooks/index.js
- api/hooks/discordChatBridge/chatBridgeChannel.js
- api/hooks/discordChatBridge/index.js
- api/hooks/gbl/index.js
- api/hooks/highPingKick/index.js
- api/hooks/playerTracking/index.js
- api/hooks/sdtdCommands/index.js
- api/hooks/sdtdLogs/index.js
- test/lifecycle.test.js
- test/unit/hooks/sdtdlogs/index.test.js
If we try to get the logging object when it doesnt exist yet, we get a vanilla event emitter that does nothing. 
Idk why I wrote this piece of code tbh, to give bugs like this a hiding place perhaps?
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/blob/master/api/hooks/sdtdLogs/index.js#L111
I vaguely remember it solved some edge case but cannot for the life of me remember why I made it like that... Should be refactored but I'm scared to break something else. For now, this should take care of the high ping kick hook
> High ping kick hook should listen to the correct LoggingObject to receive events

- api/hooks/discordChatBridge/chatBridgeChannel.js
Adds a fallback value for if player's country is falsy. Fixes #356
> Add fallback for undefined player country in Discord chatbridge rich connected messages

- api/hooks/discordBot/commands/meta/restart.js
this will prevent TypeError: Cannot read property 'split' of undefined from occurring if CSMM_ADMINS is not defined #389
> make sure CSMM_ADMINS is defined to avoid TypeError

- api/helpers/redis/del.js
- api/helpers/redis/get.js
- api/helpers/redis/incr.js
- api/helpers/redis/set.js
- api/hooks/redis.js
- package-lock.json
- package.json
- test/unit/helpers/redis/del.test.js
- test/unit/helpers/redis/get.test.js
- test/unit/helpers/redis/incr.test.js
- test/unit/helpers/redis/set.test.js
- test/unit/hooks/sdtdlogs/LoggingObject.test.js
Use `redis` instead of using the sails redis adapter.
> Reuse a single connection in redis helpers instead of requesting a new one for every operation

- api/controllers/etc/health.js
- config/routes.js
- scripts/healthcheck.js
This endpoint is less heavy than the stats endpoint but still does a DB query.
> Create dedicated healthcheck endpoint

- worker/processors/kill/index.js
Fixes #429 
Instead of using async-await within a for loop, implements `Promise.all` to parallelise the Kill Event promises.
Errors previously weren't logged, so I've added sails logging within the catch block.
> Increase performance for economy killEarner by parallelising promises

- worker/worker.js
Servers that don't respond fast were clogging up the queue
> Increase concurrency for tracking processor

- api/hooks/historicalInfo/objects/memUpdate.js
- test/unit/hooks/playerTracking/playerTracking.test.js
- worker/processors/playerTracking/index.js
Waterline was doing a select everytime delete was called. Considering these are huge tables, those are very heavy and useless selects.
> Use raw queries for deletion of tracking data

- api/helpers/get-queue-object.js
Noticed that post-job handlers sometimes couldn't find jobs. I think it's because we keep so little finished jobs around right now, this should resolve that
> Keep more jobs around after completion/failing

- worker/processors/hooks/index.js
This should fix https://sentry.io/organizations/csmm/issues/2012830130/?project=5223600&query=is%3Aunresolved
Not fix the root cause but should stop Sentry getting clogged up and hopefully help debug what's going wrong
> Exit early and log error when hooks processor doesnt get good data

- api/helpers/get-queue-object.js
This will force jobs that get stalled for whatever reason to exit.
> Add timeout to default job opts

- api/hooks/sdtdLogs/index.js
The previous implementation created problems when running on large public instances
> Move how loggingObject gets initialized

- api/hooks/sdtdLogs/LoggingObject.js
- test/unit/hooks/sdtdlogs/processor.test.js
- worker/processors/logs/index.js
So on the larger instances, CPU is super spikey with the new logging refactor.
This PR aims to spread out job execution and thus stablize CPU usage
> Add offset to logs job execution

- api/hooks/sdtdCommands/commands/claim.js
- test/unit/hooks/commands/claim.test.js
When a player tried to claim an item but the give command errored for whatever reason, the claim lock was not removed
> Fix issue in claim command after player tried to claim a bugged item

- api/controllers/SdtdServer/set-settings.js
- api/hooks/sdtdCommands/commandHandler.js
- api/models/SdtdConfig.js
- migrations/20210112215544-reply-prefix.js
- test/integration/controllers/set-settings.test.js
- test/unit/hooks/commands/commandHandler.test.js
- views/sdtdServer/partials/settings/commandSettings.sejs
This allows all CSMM replies to get a colour via CPM. A hex code like `[02f9dd]` will make everything cyan for example
> Add configurable prefix to all command replies

- .github/workflows/CI.yml
- package.json
This thing is great if your PR has code changes. When it's just dependencies, you cannot see what went wrong. Also, log output is a lot more detailed than what CRR produced.
> Remove check run reporter

- migrations/20210119173152-fix-default-values.js
Just caused log lines because Sails wasnt happy about it. Didnt actually affect any functionality afaik
> Fix usage of defaultValue in migrations

- api/controllers/SdtdServer/discordBot/check-if-bot-is-in-guild.js
- api/controllers/SdtdServer/discordBot/find-channel-by-id.js
- api/controllers/SdtdServer/discordBot/find-writeable-channels-in-guild.js
- api/controllers/SdtdServer/discordBot/get-server-roles.js
- api/controllers/SdtdServer/discordBot/set-chat-channel.js
- api/controllers/SdtdServer/discordBot/set-discord-guild.js
- api/controllers/SdtdServer/discordBot/set-notification-channel.js
- api/controllers/SdtdServer/discordBot/set-prefix.js
- api/controllers/User/find-guilds-managed-by-user.js
- api/helpers/discord/get-client.js
- api/helpers/meta/get-donator-status.js
- api/helpers/meta/load-system-stats-and-info.js
- api/hooks/customDiscordNotification/index.js
- api/hooks/discordBot/index.js
- api/hooks/discordChatBridge/index.js
- api/hooks/economy/objects/discordMessageHandler.js
- config/bootstrap.js
- test/integration/controllers/setChatChannel.test.js
- worker/worker.js
By changing the Discord client initialization logic like this, we can use the client without problems in the worker process.
In the worker, the client gets no listeners, no registered commands, etc. This essentially makes it an advanced REST client
> Refactor Discord client to be used in both processes

- worker/processors/bannedItems/handleTrackingUpdate.js
This would trip up bannedItems sometimes. Shouldn't happen very often, this was a log line when the player data was in a weird state
> Fix a bad logging call in bannedItems hook

- api/policies/canSeeTicket.js
Users who had a CSMM owner who did not own the game were unable to view tickets
> fix: permission when viewing ticket as server owner with no player-role

- api/helpers/sdtd/load-player-stats.js
- test/unit/helpers/sdtd/loadPlayerStats.test.js
- worker/processors/hooks/enrichEventData.js
- worker/processors/hooks/index.js
Hooks fire faster than Allocs can update data, this fixes that
Originally I didn't realize Allocs was returning stale data, so I made a whole helper + tests for loading stats. Didnt wanna throw it away though. Real fix for this issue is in 2nd commit
> Work around Allocs returning stale data when a hook fires

- views/sdtdServer/import.sejs
[app] 2021-04-01T20:23:42.640Z - verbose: Unable to expose body parameter `_csrf` in streaming upload!
[app] Client tried to send a text parameter (_csrf) after one or more files had already been sent.
[app] Make sure you always send text params first, then your files.
[app] (In an HTML form, it's as easy as making sure your text inputs are listed before your file inputs.
> fix: improper use of csrf header in form

- worker/processors/sdtdCommands/commands/listTele.js
- worker/processors/sdtdCommands/index.js
Loading players like we did before this patch caused problems for servers with very large amounts of active players. With this change, we load players much less frequently which should improve performance
> fix: refactor how player data gets loaded for commands

- api/controllers/SdtdServer/set-settings.js
- api/models/SdtdConfig.js
- migrations/20210605180721-servername-for-reply.js
- test/integration/controllers/set-settings.test.js
- test/unit/hooks/commands/commandHandler.test.js
- test/unit/hooks/commands/reply.test.js
- views/sdtdServer/partials/settings/commandSettings.sejs
- worker/processors/sdtdCommands/sendReply.js
Requires CPM to be installed since this uses the "pm2" command
Whenever CSMM replies to a player from a command, this will be the sender name. Useful for customizing replies more, adding a colour (RIP the ugly red :)). When not configured, will default to 'CSMM'
> Add a configurable server name to command replies

- config/customLog.js
So this was a fun one...
Disk space usage kept growing over time after some dependency updates. I assumed (wrongly ^^) that it was not rotating log files properly. Turns out, it was rotating log files HOWEVER the deleted files were still 'in use' by the process.
https://askubuntu.com/questions/413358/disk-is-full-but-cannot-find-big-files-or-folders
This might be a problem with Winston but I only saw this happening for the Docker instances. In Docker, it doesnt make much sense to log to a file. CSMM can log to stdout and let the logging infra take over.
So the 'fix' is to disable file logging :)
> feat: add a switch to allow disabling file logging

- test/unit/hooks/sdtdlogs/handleLogLine.test.js
- worker/processors/logs/handleLogLine.js
In the past, server chat was completely ignored. However, it can still be useful to hook into these log lines. These messages will now be emitted as logLines
> Don't fully ignore server chat messages

- api/hooks/sdtdLogs/eventDetectors/7d2dSSE.js
CSMM would automatically try to reconnect if it had noticed the connection went stale. This however, caused issues when it tried to reconnect to a server that was offline for a period
> fix: prevent doubling of log messages

- api/helpers/sdtd/get-player-role.js
This makes sure that the data in the database accurately reflects the players current permissions/role. It also fixes sorting players by role on the players overview page
> Write back a players role to the database after running custom business logic

- worker/processors/sdtdCommands/commands/listTele.js
- worker/processors/sdtdCommands/commands/removetele.js
- worker/processors/sdtdCommands/commands/renameTele.js
- worker/processors/sdtdCommands/commands/setTele.js
- worker/processors/sdtdCommands/commands/telePublic.js
- worker/processors/sdtdCommands/commands/teleprivate.js
The tp commands only have a few aliases which are inconsistent between the commands and do not completely represent industry standard aliases for similar commands in other systems. This changeset adds aliases to improve those consistency and familiarity factors.
> Add more aliases to tp

- api/hooks/sdtdLogs/eventDetectors/7d2dSSE.js
There's many reasons that an error occurs and we should not always clear this flag. This change will cause the system to be a bit slower when having to retry connections, but will be more fault tolerant
> fix: do not clear isConnecting flag on errors

- api/helpers/economy/deduct-from-player.js
- api/helpers/economy/delete-old-data.js
- api/helpers/economy/give-to-player.js
- api/hooks/historicalInfo/objects/memUpdate.js
- config/bootstrap.js
- config/custom.js
- test/unit/hooks/playerTracking/playerTracking.test.js
- worker/processors/playerTracking/index.js
- worker/processors/system/historicalDataCleanup.js
- worker/processors/system/index.js
By putting it inside the worker, we can reduce the load on the system significantly. With the old implementation, there was also a bug where multiple deletes where happening at the same time.
> fix: refactor how old data gets deleted

- worker/processors/sdtdCommands/index.js
This is bad when people are moving to Takaro and have certain CSMM commands disabled. Causes confusion for players
> fix: do not send command disabled message
