CatalysmsServerManager/7-days-to-die-server-manager

- api/helpers/get-queue-object.js
- api/hooks/sdtdLogs/LoggingObject.js
- api/hooks/sdtdLogs/logProcessor.js
- test/integration/controllers/BannedItemList.test.js
- test/lifecycle.test.js
* Add some simple simple tests for banned item lists
* Add SdtdConfig to the test objects for the banned item tests
* Switch creating bull object to helper so it can be overriden easy by tests (couldn't figure it out, put hack inside helper for now)
* More centralizing redis support so REDISSTRING isn't everywhere / less failure on no redis (Not sure if this is a good change, functionally fine, but uses cache connection which may not be right)
> More Tests

- api/controllers/CommandReply/get-reply.js
- package-lock.json
- package.json
- test/integration/controllers/CommandReply.test.js
- test/lifecycle.test.js
Command reply tests, and make sure serverid is always provided for get
Add mockdate to make sure all tests return the same date every time
> Replly tests

- api/hooks/sdtdLogs/logProcessor.js
- test/integration/hooks/sdtdLogs/logProcessor.test.js
Looks like I broke it in #67
It was checking to see if the line was not undefined. I changed it to be not falsy
https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/pull/67/files#diff-122b352c52c0406903f0a7a2ab2e9263L62
So apparently I flipped the conditional
> if there is a parsed log line, then return it, otherwise ignore it

- .github/release-drafter.yml
> Set up release drafter

- api/hooks/discordNotifications/DiscordNotification.js
- api/hooks/discordNotifications/notifications/playerConnected.js
- api/hooks/discordNotifications/notifications/playerDisconnected.js
- test/unit/hooks/discordNotifications/DiscordNotification.test.js
- test/unit/hooks/discordNotifications/notifications/playerConnected.test.js
- test/unit/hooks/discordNotifications/notifications/playerDisconnected.test.js
* Added tests
* Mostly supporting event.player being unset for whatever reason
> Fix discord notifications from crashing when not enough data

- create_tables.js
Make sure dotenv is loaded. Force env to be dev, and load in production config file so 'migrations' are done. Create the 'on' before trying to load to make sure its registered?
> fix up create_tables.js

- db-modifications.sql
This file adds more indexes to the database to improve performance
> Add db-modifications.sql

- api/controllers/SdtdServer/get-mod-version.js
- api/controllers/tracking-info/set-inventory-tracking.js
- api/helpers/sdtd/check-mod-version.js
- package-lock.json
- package.json
- test/integration/controllers/set-inventory-tracking.test.js
- test/integration/hooks/discordChatBridge/chatBridgeChannel.test.js
- test/integration/hooks/sdtdLogs/logProcessor.test.js
- test/lifecycle.test.js
- test/unit/helpers/sdtd/check-mod-version.test.js
- test/unit/hooks/discordNotifications/notifications/playerConnected.test.js
- test/unit/hooks/discordNotifications/notifications/playerDisconnected.test.js
Fixes ... a bug I don't have a stacktrace for anymore. Essentially the check for above 26 was failing on enabling tracking
> Handle all parsing of getting alloc version in one place

- api/hooks/sdtdLogs/LoggingObject.js
- api/hooks/sdtdLogs/index.js
- test/unit/hooks/sdtdlogs/LoggingObject.test.js
Eslint got run so its going to be hard to review, i'm sorry
Mostly define variables so they are not defined.
Make sure setlogline is called everywhere
make sure last success is updated
> Add tests and simplify the LoggingObject

- config/customLog.js
This will let our logging infrastructure pick up logs easier
> Log to stdout by default

- api/controllers/Player/give-item.js
- test/integration/controllers/give-item.test.js
> Give item results in a timneout error

- api/hooks/sdtdLogs/LoggingObject.js
- test/unit/hooks/sdtdlogs/LoggingObject.test.js
> Add test for active flag in LoggingObject

- .github/release-drafter.yml
> Extend release drafter

- api/hooks/discordBot/commands/sdtd/serverInfo.js
- test/lifecycle.test.js
- test/unit/hooks/discordCommands/serverInfo.test.js
> Game difficulty reported twice on Discord command

- views/includes/applicationNav.ejs
- views/includes/header.ejs
> Donate link is broken

- lefthook.yml
- package-lock.json
- package.json
> Install lefthook for better git hooks

- api/helpers/sdtd/fill-custom-variables.js
- test/unit/helpers/sdtd/fill-custom-variables.test.js
fixes #118 
I don't know how to add documentation for this.
Test cases show the examples. I decided to make it just not run if the values provided are not correct, instead of trying to return a random error message, but I can refactor it.
> Add randNum variable - fixes #118

- api/hooks/countryBan/index.js
> Remove debug log line in country ban

- views/sdtdServer/partials/settings/commandSettings.ejs
- views/sdtdServer/partials/settings/editCommandModal.ejs
> Sort the custom commands

- api/helpers/etc/parse-cron-job.js
> Quick fix for TypeError: Cannot read property 'command' of undefined

- api/hooks/sdtdLogs/index.js
- test/unit/hooks/sdtdlogs/index.test.js
> Country not properly updated when players connect to a server

- api/controllers/SdtdServer/settings.js
- test/integration/controllers/settings.test.js
> Regression in settings page

- .github/workflows/CI.yml
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
> Build on pull request

- package-lock.json
- package.json
Don't blindly upgrade semver major changes...
> Revert dotenv upgrade

- api/hooks/highPingKick/index.js
- api/utils.js
or highkingpick as my keyboard keeps trying to do
https://sentry.io/organizations/csmm/issues/1833915657/?project=5223600&query=is%3Aunresolved
> fix highpingkick

- api/hooks/discordBot/commands/meta/export-server.js
- api/hooks/discordBot/commands/meta/import-server.js
> Deprecate/remove Discord import/export

- api/controllers/AuthController.js
- api/helpers/discord/discordRequest.js
- api/helpers/discord/set-role-from-discord.js
- api/hooks/discordBot/roles/handleRoleUpdate.js
- test/lifecycle.test.js
- test/unit/helpers/discord/setRoleFromDiscord.test.js
- test/unit/hooks/discordBot/handleRoleUpdate.test.js
> Sync Discord and CSMM roles when a user (re)connects their Discord profile

- api/controllers/Shop/listing-buy.js
- test/integration/controllers/shop.test.js
- test/unit/helpers/discord/setRoleFromDiscord.test.js
- test/unit/hooks/discordBot/handleRoleUpdate.test.js
> Economy modifiers set by roles are not applied to shop items

- api/controllers/Shop/listing-add.js
- api/helpers/sdtd/validate-item-name.js
- test/integration/controllers/shop.test.js
> Shop item validation does not support custom items with spaces

- api/helpers/etc/parse-cron-job.js
- api/hooks/cron/index.js
- test/unit/hooks/cron/cron.test.js
- worker.js
Fixes #297
Just a quick fix and test right now, in the future we should move to Discord webhooks
> Fix cron module does not send notifications

- api/helpers/sdtd/execute-custom-cmd.js
The previous implementation sometimes revealed sensitive info
> Adjust error handling for custom commands so it returns saner error messages

- api/hooks/highPingKick/index.js
- api/utils.js
- test/unit/hooks/highPingKick/index.test.js
- worker.js
Potentially fix #333 by making start/stop commands bound properly since they get called as external statics even though they are not one
> Fix bad ping count checker (yet again)

- views/player/partials/giveItemButton.ejs
Added tip on quality input -- 0 for items that do not support quality.
Corrected C+V error on quality validation
> Fix quality validation when giving items to a player via dashboard

- api/hooks/highPingKick/index.js
- test/unit/hooks/highPingKick/index.test.js
on('memUpdate', this.handler) wasn't passing this properly, so while
the handler was tested, it wasn't setup right
can't use on(this.handler.bind()) because it wouldn't remove properly
Solution:
* Create new bound wrapper that calls the full function, this is easier
than binding in constructor and worrying about overrides or anything
else
* Change tests to start then call the emit function
* Wrap the emit function so we can wait for all promises to finish
before checking results in tests
> Fix highpingkick, add massive more test coverage

- .eslintignore
- api/hooks/discordNotifications/notifications/cronJob.js
- test/lifecycle.test.js
- test/unit/hooks/discordNotifications/notifications/cronJob.test.js
> Truncate cronjob notifications that are too long to send to discord

- package-lock.json
- package.json
Was going through dependabot PRs and noticed this dep is unused now
> Remove rand-token

- api/controllers/SdtdServer/execute-command.js
- assets/js/sdtdServer/console.js
- config/routes.js
- package.json
- test/integration/controllers/execute-command.test.js
> Handle errors better when executing commands via the dashboard

- api/hooks/discordBot/commands/sdtd/status.js
- test/unit/hooks/discordCommands/status.test.js
Uses `ggs BloodMoonDay` to determine the number of days in-game until the next bloodmoon 
resolves #327
> Use ggs BloodMoonDay to determine next bloodmoon

- api/policies/roles/manageServer.js
- package-lock.json
- package.json
- test/unit/policies/manageServer.test.js
Adds an if check to ensure server has been found, if no server was found returns a badRequest.
fixes #319
> Add check to verify that a server has been found in manageServer policy

- api/hooks/sdtdLogs/LoggingObject.js
- api/hooks/sdtdLogs/index.js
- test/unit/hooks/sdtdlogs/index.test.js
Something I noticed before releasing
> Fix loggingHook initializing servers that are set to inactive

- .env.example
> remove default CSMM admins

- api/controllers/Player/give-item.js
- test/integration/controllers/give-item.test.js
This PR aims to fix: https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/issues/324
* added the double-quotes
* added an item with a space to ensure that the test case passes in such a scenario
> Fix issue when trying to give items with spaces in the name via player profile page

- views/sdtdServer/partials/settings/commandSettings.sejs
> Fix custom command edit button rendering out of order

- api/controllers/BannedItemList/set-banned-item-status.js
- api/helpers/meta/set-server-inactive.js
- api/hooks/bannedItems/index.js
- api/hooks/bullboard.js
- api/hooks/playerTracking/index.js
- test/unit/hooks/bannedItems/bannedItems.test.js
- test/unit/hooks/playerTracking/playerTracking.test.js
- worker/processors/bannedItems/handleTrackingUpdate.js
- worker/processors/bannedItems/index.js
- worker/worker.js
> Move bannedItems hook to worker process

- api/helpers/get-queue-object.js
- api/hooks/sdtdLogs/LoggingObject.js
> Add default options for how many Bull jobs are kept in history

- api/helpers/get-queue-object.js
Instead of creating new ones for every call, we reuse the existing Queue object. This avoids having to create new Redis connections.
This solves the max Redis clients issue but was also a memory leak, probably
> Reuse Bull Queue objects instead of creating new objects

- api/hooks/sdtdLogs/LoggingObject.js
- test/unit/hooks/sdtdlogs/LoggingObject.test.js
> Handle bad background data for background jobs

- package-lock.json
- package.json
Add lint staged:
Issue: https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/issues/435
> Add lint staged

- Dockerfile
- api/controllers/SdtdServer/discordBot/check-if-bot-is-in-guild.js
- api/controllers/SdtdServer/discordBot/find-channel-by-id.js
- api/controllers/SdtdServer/discordBot/find-writeable-channels-in-guild.js
- api/controllers/SdtdServer/discordBot/get-server-roles.js
- api/controllers/SdtdServer/discordBot/set-chat-channel.js
- api/controllers/SdtdServer/discordBot/set-discord-guild.js
- api/controllers/SdtdServer/discordBot/set-notification-channel.js
- api/controllers/SdtdServer/discordBot/set-prefix.js
- api/controllers/User/find-guilds-managed-by-user.js
- api/helpers/meta/get-donator-status.js
- api/helpers/meta/load-system-stats-and-info.js
- api/hooks/customDiscordNotification/index.js
- api/hooks/discordBot/commands/meta/import-server.js
- api/hooks/discordBot/commands/sdtd/execCommand.js
- api/hooks/discordBot/index.js
- api/hooks/discordBot/util/createEmbed.js
- api/hooks/discordChatBridge/index.js
- package-lock.json
- package.json
- test/integration/controllers/setChatChannel.test.js
- test/unit/hooks/discordCommands/serverInfo.test.js
- test/unit/hooks/discordCommands/status.test.js
- test/unit/hooks/discordNotifications/DiscordNotification.test.js
- test/unit/hooks/discordNotifications/notifications/cronJob.test.js
- test/unit/hooks/discordNotifications/notifications/gblMaxBan.test.js
- worker/processors/discordNotification/notifications/cronJob.js
> Upgrade Discordjs version

- package-lock.json
- package.json
> Switch to concurrently to attempt to make it easier to debug startup issues

- api/helpers/meta/load-system-stats-and-info.js
- api/helpers/meta/start-usage-stats-gathering.js
- migrations/20201110094358-add-index-public-teleports.js
- migrations/20201110095817-add-index-analytics.js
Basically some low hanging fruit that should make quite a difference. If it doesn't, at least the logs volume will go down :)
> Initial performance improvements wrt slow queries

- worker/processors/hooks/index.js
Fixes https://sentry.io/organizations/csmm/issues/2073812236/?project=5223600&query=is%3Aunresolved
> Ensure server data is available in eventData

- api/hooks/sdtdCommands/replyTypes.js
> Fix default response for who command

- api/hooks/sdtdCommands/commands/claim.js
- api/hooks/sdtdCommands/replyTypes.js
- test/unit/hooks/commands/claim.test.js
> Let players control how many items get claimed in one go

- api/helpers/etc/parse-cron-job.js
- api/helpers/sdtd/parse-commands-string.js
- api/hooks/sdtdCommands/customCommand.js
- package-lock.json
- package.json
- test/unit/helpers/sdtd/parse-command-string.test.js
- worker/processors/bannedItems/handleTrackingUpdate.js
- worker/processors/hooks/index.js
> Fix customCommands that include a ; get split at places they shouldn't be

- api/controllers/BannedItemList/add-banned-item.js
- api/controllers/BannedItemList/create-banned-item-tier.js
- api/controllers/BannedItemList/delete-banned-item-tier.js
- api/controllers/BannedItemList/get-banned-items.js
- api/controllers/BannedItemList/get-tiers.js
- api/controllers/BannedItemList/remove-banned-item.js
- api/controllers/SdtdServer/settings.js
- api/models/BannedItem.js
- api/models/BannedItemTier.js
- api/models/SdtdConfig.js
- config/routes.js
- migrations/20210106121218-bannedItemTiers.js
- test/integration/controllers/BannedItemList.test.js
- test/unit/hooks/bannedItems/bannedItems.test.js
- views/sdtdServer/partials/settings/bannedItemList.sejs
- worker/processors/bannedItems/handleTrackingUpdate.js
> Add tiers to banned items module

- migrations/20210106121218-bannedItemTiers.js
So turns out, in production data can have some weird forms..
> Fix bannedItem migration

- api/helpers/roles/check-permission.js
- test/unit/helpers/roles/check-permission.test.js
This will significantly improve performance when executing many permission checks close to each other. Mainly targeting the map rendering on dashboard with this change
> Add a cache for permission checks

- api/controllers/tracking-info/purge.js
Also removed a count which will improve performance
> fix: bad log line in purge tracking data

- views/player/partials/giveItemButton.sejs
- views/sdtdServer/economy/shop.sejs
> Make item suggestions case insensitive

- test/integration/cron-job/cron.test.js
Repro case for a possible bug reported on Discord
> chore: add test for cron test route

- test/unit/helpers/sdtd/execute-custom-command.test.js
- worker/util/Handlebars.js
- add an alias for sum/add handlebars helper
- randList
- randNum
I know randNum and randList already exist for custom commands. However, the implementation there was not trivial to refactor so it works for both systems and I'm lazy so I ~copy pasted~ reimplemented the helpers
> Small additions to Handlebars system

- api/controllers/SdtdServer/teleports/add-teleport.js
- api/controllers/SdtdServer/teleports/delete-teleport.js
- api/controllers/SdtdServer/teleports/get-teleport.js
- api/models/SavedTeleport.js
- config/routes.js
- migrations/20210602180548-teleportation-saves.js
- test/integration/controllers/savedTeleports.test.js
- views/player/partials/teleportPlayerButton.sejs
> Teleportation Saves

- worker/processors/sdtdCommands/sendReply.js
Thanks @Aviator-Coding for bringing this up :)
> chore: change a let to const

- api/controllers/cron-job/cron-import.js
- test/integration/controllers/cron/cron-import.test.js
> Tolerate CPM command in cron import

- api/hooks/sdtdLogs/eventDetectors/7d2dSSE.js
- test/unit/hooks/sdtdlogs/SSE.test.js
- worker/processors/logs/handleLogLine.js
> fix: double chat message detection when SSE is used and mods are handling the messages

- api/hooks/sdtdLogs/enrichers/index.js
- api/hooks/sdtdLogs/enrichers/playerDied.js
This should ensure we always get the latest, most correct data.
> Use online players api for getting last death data

- api/controllers/Playground/get-meta.js
- config/routes.js
- test/unit/helpers/CSMMCommand/getHelpers.js
- worker/util/CSMMCommand/index.js
Adds a HTTP route to retrieve metadata about Handlebars. Used in playground for completion items
> Meta route for playground

- api/hooks/sdtdLogs/eventDetectors/7d2dSSE.js
This should survive any game server or physical server restarts
> fix: make SSE reconnection logic more robust

- api/controllers/SdtdServer/get-players-datatable.js
- views/sdtdServer/players.sejs
> feat: Adding "Sort" toggle to roles column in player overview screen

- views/sdtdServer/dashboard.sejs
- views/sdtdServer/playersTable.sejs
+ adjusted height of the Table in the Server-Dashboard
+ FIX: Table
State gets restored now
> fix(Playertable): Restore State + height

- Dockerfile
This change let me build the image :)
> ci: install python3 in docker env

- api/hooks/sdtdLogs/eventDetectors/7d2dSSE.js
> TypeError: Request path contains unescaped characters

- package-lock.json
- package.json
Release drafter is broken, think this is why...
> update dev with latest version info 

- worker/util/Handlebars.js
```
{{#if (gt (occurrences (execCmd "version") "CSMM Patrons") 0)}}
CPM is installed!    
{{/if}}
```
> Add `execCmd` helper to Handlebars

- test/unit/helpers/sdtd/execute-custom-command.test.js
- worker/util/Handlebars.js
Helper for checking if a date has passed.
> feat: datePassed helper

- api/controllers/Player/ban.js
this solves issue…s with banning XBL_ players)
> fix: use cross ID as argument when banning players

- api/hooks/discordBot/commands/execCommand.js
- api/hooks/discordBot/commands/listServers.js
- api/hooks/discordBot/commands/lookup.js
- api/hooks/discordBot/commands/player.js
- api/hooks/discordBot/commands/status.js
- api/hooks/discordBot/commands/top.js
- api/hooks/discordBot/index.js
Since a lot of commands need to do API requests to the gameserver, it can take quite some time. By using deferReply, we get a lot more time before the interaction timeouts.
> Fix timeout of slash command reply if API requests to gameserver take too long

- test/unit/helpers/sdtd/execute-custom-command.test.js
- worker/util/Handlebars.js
> feat: increase maximum number of iterations with times helper to 250

- api/hooks/sdtdLogs/eventDetectors/7d2dSSE.js
- worker/util/throttledFunction.js
allow certain errors to be dropped before it being counter against throttle limits
> feat: more flexible throttling

- api/hooks/sdtdLogs/eventDetectors/7d2dV1SSE.js
> chore: ignore warn log lines about velocity of a kinematic body

- api/hooks/sdtdLogs/index.js
- worker/processors/logs/handleLogLine.js
chatMessages dont include playerName anymore...
> fix chat message detection
